# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "**" ]
    paths:
    - src/**
    - test/**
  release:
    types: [ "published" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      matrix:
        node-version: [18.x] #[14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run lint
    - run: npm run test
      if: always()
    - run: npm run package
      if: always()
    - name: Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
          files: "*.vsix"
